# Generated by Django 5.0.7 on 2024-08-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBackend', '0003_user_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
                ('message', models.TextField()),
                ('reaction', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.CharField(max_length=10000),
        ),
    ]
