# Generated by Django 5.0.7 on 2024-08-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBackend', '0004_posts_delete_user_alter_items_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='username',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
